### PR TITLE
lede-ify ffffm-packages

### PR DESCRIPTION
**Pull request by christf**
- [x] ffffm-banner
- [x] ffffm-autoupdater-use-site-conf-branch
- [x] ffffm-keep-radio-channel

### CODE REVIEW

**Comment by rubo77** [comment]
I also started, but there seems to be something odd:
https://github.com/rubo77/ffm-packages/commit/5388bab0a8bd5af7266a8782fbd9894513d4b646

This doesn't build yet

**Comment by rubo77** [comment]
If I build with my modification I get

```
ERROR: please fix feeds/packages_button/ffffm-autoupdater-use-site-conf-branch/Makefile - see logs/feeds/packages_button/ffffm-autoupdater-use-site-conf-branch/dump.txt for details
ERROR: please fix feeds/packages_button/ffffm-button-bind/Makefile - see logs/feeds/packages_button/ffffm-button-bind/dump.txt for details
ERROR: please fix feeds/packages_button/ffffm-disable-80211b/Makefile - see logs/feeds/packages_button/ffffm-disable-80211b/dump.txt for details
ERROR: please fix feeds/packages_button/ffffm-enlarge-dns-cache/Makefile - see logs/feeds/packages_button/ffffm-enlarge-dns-cache/dump.txt for details
ERROR: please fix feeds/packages_button/ffffm-keep-radio-channel/Makefile - see logs/feeds/packages_button/ffffm-keep-radio-channel/dump.txt for details
ERROR: please fix feeds/packages_button/ffffm-luci-set-mtu/Makefile - see logs/feeds/packages_button/ffffm-luci-set-mtu/dump.txt for details
ERROR: please fix feeds/packages_button/gluon-dns-cache/Makefile - see logs/feeds/packages_button/gluon-dns-cache/dump.txt for details
....
Configuration failed:
 * unable to enable package 'ffffm-button-bind'
Makefile:93: die Regel für Ziel „config“ scheiterte

```

und

```
cat logs/feeds/packages_button/ffffm-button-bind/dump.txt
Makefile:9: *** missing separator.  Stop.
```

**Comment by rubo77** [comment]
Now It starts building, but after 10 minutes I get the error:

```
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
/media/workspace/gluon-build/gluon/lede/include/toplevel.mk:198: recipe for target 'world' failed
make[1]: *** [world] Error 1
make[1]: Leaving directory '/media/workspace/gluon-build/gluon/lede'
Makefile:125: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by rubo77** [comment]
with V=s I get

```
cp -fpR ./luasrc /media/workspace/gluon-build/gluon/lede/build_dir/target-mips_24kc_musl-1.1.16/ffffm-button-bind/luadest/
cp: cannot stat './luasrc': No such file or directory
Makefile:39: recipe for target '/media/workspace/gluon-build/gluon/lede/build_dir/target-mips_24kc_musl-1.1.16/ffffm-button-bind/.built' failed
make[4]: *** [/media/workspace/gluon-build/gluon/lede/build_dir/target-mips_24kc_musl-1.1.16/ffffm-button-bind/.built] Error 1
make[4]: Leaving directory '/media/workspace/gluon-build/gluon/packages/button/ffffm-button-bind'
package/Makefile:105: recipe for target 'package/feeds/packages_button/ffffm-button-bind/compile' failed
make[3]: *** [package/feeds/packages_button/ffffm-button-bind/compile] Error 2
make[3]: Leaving directory '/media/workspace/gluon-build/gluon/lede'
package/Makefile:101: recipe for target '/media/workspace/gluon-build/gluon/lede/staging_dir/target-mips_24kc_musl-1.1.16/stamp/.package_compile' failed
make[2]: *** [/media/workspace/gluon-build/gluon/lede/staging_dir/target-mips_24kc_musl-1.1.16/stamp/.package_compile] Error 2
make[2]: Leaving directory '/media/workspace/gluon-build/gluon/lede'
/media/workspace/gluon-build/gluon/lede/include/toplevel.mk:198: recipe for target 'world' failed
make[1]: *** [world] Error 2
make[1]: Leaving directory '/media/workspace/gluon-build/gluon/lede'
Makefile:125: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by christf** [comment]
to avoid any confusion: the code in this PR builds. the other one is (was) broken.

**Comment by rubo77** [comment]
I corrected my branch, the lua files had to be moved in the right location: https://github.com/rubo77/ffm-packages/commit/f4ccd094a30e7b9d27bb746389f3cf142a2af234

**Comment by rubo77** [comment]
After adapting the config mode admin files, I managed to get a menu in config mode, but there seems to be a problem with multiple radio boxes in the new gluon-web:

**Comment by rubo77** [comment]
there was still missing this line when you use luaDiet:

    $(CP) $(PKG_BUILD_DIR)/luadest/* $(1)/

**Comment by rubo77** [comment]
Admin page of button-bind works as expected now with a selectbox instead of radio buttons:

https://github.com/rubo77/ffm-packages/blob/2017.1.x/ffffm-button-bind/luasrc/lib/gluon/web/model/admin/button-bind.lua#L19

But unfortunately the rfkill button has **no effect** on my WR842v1

Seems like in lede something changed in the system. maybe it is not possible to create such a temp file in /tmp/ any more?

**Pull request merged**
