### PR TITLE
button-bind lede adaptions

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by rubo77** [comment]
This works and builds, but it seems like the rfkill script doesn't work correctly on lede still

**Comment by christf** [comment]
@rubo77 why switching to selectboxes?

**Comment by rubo77** [comment]
Radio Buttons are not correctly implemented in lede

**Comment by rubo77** [comment]
See https://github.com/freifunk-ffm/packages/pull/32#issuecomment-332968586

@Neoraider said in IRC, this has to be fixed in gluon, one day.

So select options are the only option atm.

**Comment by rubo77** [comment]
Did you find the time to test this? And why the rfkill script doesn't work in lede?

**Comment by rubo77** [comment]
Did you find the time to test this? And why the rfkill script doesn't work in lede?

**Comment by oszilloskop** [comment]
We don't found time for testing yet.

**Comment by rubo77** [comment]
since 31.1.2018 radkiobuttons are fixed in gluon master cfe1bba8ae1f3c4d34e2b5581d2c12fd88f6e60c

But I think this will not be backported to 2017.1.x, so select-menues still are the needed change here.

still open:

>  the rfkill script doesn't work correctly on lede still

**Comment by rubo77** [comment]
I adapted the package to the gluon master (2018.1.x): https://github.com/rubo77/ffm-packages/commit/1abb767553429bac6a7031ac6882dce7ce225013

I will test the button there on a 1043N v5 now...

**Pull request closed without merging**
